List<String> quotes = [
  "A good teacher is a master of simplification and an enemy of simplism.",
  "The best way to teach is to inspire.",
  "A good teacher is like a good wine, it only gets better with age.",
  "The best teachers teach from the heart, not from the book.",
  "The best teachers are those who inspire you to teach yourself.",
  "The most important thing a teacher can do is to respect the student.",
  "Teaching is the art of assisting discovery.",
  "Teaching is not a lost art, but the regard for it is a lost tradition.",
  "A teacher is one who makes himself progressively unnecessary.",
  "The best teacher is the one who teaches from the heart, not from the book.",
  "Teaching is the highest form of understanding.",
  "A good teacher is a person who can make a difference in a student's life.",
  "The best teachers are those who lead by example.",
  "The best teachers are those who make themselves redundant.",
  "A teacher is a gardener who cultivates the minds of his students.",
  "The best teachers are those who make learning fun.",
  "A good teacher is one who makes learning a joyous experience.",
  "A teacher's role is to inspire, not to dictate.",
  "A teacher's most important job is to create a love for learning.",
  "A good teacher is one who makes a difference in a student's life.",
  "A great teacher is one who makes learning a journey of discovery.",
  "A teacher's role is to be a guide, not a dictator.",
  "A teacher's role is to foster curiosity and creativity.",
  "A teacher's role is to inspire a love for learning that is lifelong.",
  "A great teacher is one who is able to make learning fun and engaging.",
];
