List<String> quotes = [
  "The greatest gift of the teacher is to awaken joy in creative expression and kno - Louis wledge.",
  "A good teacher is a master of simplification and an enemy of simplism.",
  "The best teachers are those who show you where to look, but don't tell you what to see."
      "The best way to teach is to inspire.",
  "A good teacher is like a good wine, it only gets better with age.",
  "The best teachers teach from the heart, not from the book.",
  "The best teachers are those who inspire you to teach yourself.",
  "The most important thing a teacher can do is to respect the student.",
  "Teaching is the art of assisting discovery.",
  "The mediocre teacher tells. The good teacher explains. The superior teacher demonstrates. The great teacher inspires.",
  "The best teacher is the one who suggests rather than dogmatizes, and inspires his listener with the wish to teach himself.",
  "A teacher is a compass that activates the magnets of curiosity, knowledge, and wisdom in the pupils.",
  "Teaching is not a lost art, but the regard for it is a lost tradition.",
  "A teacher is one who makes himself progressively unnecessary.",
  "The best teacher is the one who teaches from the heart, not from the book.",
  "A great teacher is a great artist and there are as few as there are any other great artists. Teaching might even be the greatest of the arts since the medium is the human mind and spirit.",
  "Teaching is the highest form of understanding.",
  "A good teacher is a person who can make a difference in a student's life.",
  "The best teachers are those who lead by example.",
  "A teacher's job is not to create students in his own image, but to develop students who can create their own image.",
  "The best teachers are those who make themselves redundant.",
  "A teacher is a gardener who cultivates the minds of his students.",
  "The best teachers are those who make learning fun.",
  "A teacher's role is not to be the fountain of knowledge, but to be the facilitator of learning.",
  "A good teacher is like a good book, it opens the mind and expands the imagination.",
  "A great teacher is not the one who gives the most information, but the one who most ignites the student's curiosity.",
  "The best teachers are those who are able to adapt to the learning style of each student.",
  "A teacher's role is not just to teach what is written in the book, but to teach what is not written in the book.",
  "A good teacher is one who makes learning a joyous experience.",
  "A teacher's role is to inspire, not to dictate.",
  "A teacher's most important job is to create a love for learning.",
  "A good teacher is one who makes a difference in a student's life.",
  "A teacher's role is not just to impart knowledge, but to inspire and motivate.",
  "A great teacher is one who makes learning a journey of discovery.",
  "A good teacher is one who creates a positive and supportive classroom environment.",
  "A teacher's role is to be a guide, not a dictator.",
  "The best teachers are those who create a classroom culture of respect and kindness.",
  "A teacher's role is to foster curiosity and creativity.",
  "A good teacher is one who values the unique strengths and abilities of each student.",
  "A teacher's role is to help students discover their own potential.",
  "A great teacher is one who empowers students to take ownership of their own learning.",
  "A good teacher is one who is able to connect with each student on a personal level.",
  "A teacher's role is to help students develop critical thinking skills.",
  "The best teachers are those who are able to create a sense of community in the classroom.",
  "A teacher's role is to inspire a love for learning that lasts a lifetime.",
  "A good teacher is one who encourages students to take risks and think outside the box.",
  "A teacher's role is to challenge students to reach their full potential.",
  "A great teacher is one who is able to connect the material to real-world applications.",
  "A good teacher is one who is able to create a safe and inclusive classroom environment.",
  "A teacher's role is to provide opportunities for students to develop their problem-solving skills.",
  "The best teachers are those who are able to build positive relationships with their students.",
  "A teacher's role is to provide a supportive and nurturing learning environment.",
  "A good teacher is one who is able to create a sense of belonging in the classroom.",
  "A teacher's role is to inspire a love for learning that is lifelong.",
  "A great teacher is one who is able to make learning fun and engaging.",
  "A good teacher is one who is able to create a classroom culture of teamwork and collaboration.",
  "A teacher's role is to help students develop self-awareness and self-regulation.",
  "The best teachers are those who are able to create a sense of purpose and meaning in the classroom.",
  "A teacher's role is to provide opportunities for students to develop their leadership skills.",
  "A good teacher is one who encourages student's to be independent thinkers.",
  "A teacher's role is to provide a challenging and stimulating learning environment.",
  "A great teacher is one who is able to create a classroom culture of positivity and optimism.",
  "A good teacher is one who is able to build trust and rapport with their students.",
  "A teacher's role is to provide opportunities for students to develop their creativity.",
  "The best teachers are those who are able to make learning relevant to students' lives.",
  "A teacher's role is to foster a sense of curiosity and wonder in students.",
  "A great teacher is one who is able to create a learning environment that is both challenging and supportive.",
  "A good teacher is one who is able to create a classroom culture of collaboration and cooperation.",
  "A teacher's role is to provide opportunities for students to develop their communication skills.",
  "The best teachers are those who are able to create a classroom culture of inclusivity and diversity.",
  "A teacher's role is to foster a sense of self-efficacy in students.",
  "A good teacher is one who is able to create a classroom environment that is stimulating and engaging.",
  "A teacher's role is to help students develop their emotional intelligence.",
  "A great teacher is one who is able to create a classroom culture of mutual respect and understanding.",
  "A good teacher is one who is able to create a safe and welcoming classroom environment.",
  "A teacher's role is to provide opportunities for students to develop their time-management and organizational skills.",
  "The best teachers are those who are able to create a classroom culture of positive reinforcement and encouragement.",
  "A teacher's role is to provide opportunities for students to develop their problem-solving and critical thinking skills.",
  "A good teacher is one who is able to create a classroom culture of open-mindedness and curiosity.",
  "A teacher's role is to foster a sense of self-motivation and self-discipline in students.",
  "A great teacher is one who is able to create a classroom culture of respect for diversity and different perspectives.",
  "A good teacher is one who is able to create a classroom environment that is both stimulating and supportive.",
  "A teacher's role is to help students develop their decision-making and conflict-resolution skills.",
  "The best teachers are those who are able to create a classroom culture of safety and trust.",
  "A teacher's role is to provide opportunities for students to develop their creativity and imagination.",
  "A good teacher is one who is able to create a classroom culture of active engagement and participation.",
  "A teacher's role is to foster a sense of curiosity and a love of learning in students.",
  "A great teacher is one who is able to create a classroom culture of positivity and optimism.",
  "A good teacher is one who is able to create a classroom environment that is inclusive and respectful of diversity.",
  "A teacher's role is to provide opportunities for students to develop their interpersonal skills.",
  "The best teachers are those who are able to create a classroom culture of trust and openness.",
  "A teacher's role is to foster a sense of self-awareness and self-regulation in students.",
  "A good teacher is one who is able to create a classroom culture of collaboration and teamwork.",
  "A teacher's role is to provide opportunities for students to develop their leadership skills.",
  "A great teacher is one who is able to create a classroom culture of mutual respect and understanding.",
];
